# Generated by Django 3.1.6 on 2021-04-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='SOME STRING')),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ManyToManyField(null=True, to='main.Skill_Name')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, default='ShotbyMistake.png', null=True, upload_to='')),
                ('website_name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(null=True, to='main.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Other_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, default='ShotbyMistake.png', null=True, upload_to='')),
                ('website_name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(null=True, to='main.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ManyToManyField(null=True, to='main.About_Name')),
            ],
        ),
    ]
